name: Android CI

on:
  push:
    branches: [ master ]
  workflow_dispatch: # 允许手动点击按钮触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 下载源码（自动处理子模块，解决 Dobby 缺失问题）
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 2. 配置 Java 环境
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # 3. 配置 Ninja 编译工具
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      # 4. 赋予脚本执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. 开始构建 Debug 包 (不需要签名密码)
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 6. 上传构建好的 APK 供你下载
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Zhiliao-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
